apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  namespace: vkpaints-dev-ns
spec:
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-container
        image: shubha20/vk-paints_product-service:v1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: product-config
        # - secretRef:
        #     name: product-secret
        ports:
        - containerPort: 3000