apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: vkpaints-dev-ns
spec:
  selector:
    app: product-service
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
